### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by Sozdy** [SWEET1S/moonshine-roles-permissions#1]
```
7. In the AuthServiceProvider.php file, add the following ( Super Admin Role ):

use Illuminate\Support\Facades\Gate;

public function boot()
{
    Gate::before(function ($user, $ability) {
        return $user?->role?->id === 1;
    });
}
```

Line error:
    `return $user?->role?->id === 1;`
With this option, all users whose `role?->id !== 1 `will be denied access

Correct option:
    `return $user?->role?->id === 1 ? true : null;`

**Comment by SWEET1S** [comment]
Yes, you are absolutely right, I corrected the error. Thank you so much for writing.
