### ISSUE TITLE
A small error in the readme.md file leads to issues when installing the package according to the instructions provided in the readme.md

### ISSUE THREAD

**Issue by carma100** [SWEET1S/moonshine-roles-permissions#2]
Hello!

In the installation documentation for the 'moonshine-roles-permissions' package, there is no information about using the 'spatie/laravel-permission': '^5.11' package. If you run the command 'composer require sweet1s/moonshine-roles-permissions,' it installs version 1.2^ in which the 'Traits' are missing, making further configuration impossible. Therefore, please add information to the Readme.md file about the need for 'Spatie Laravel Permissions ^6'. Thank you.

![The traits folder is missing](https://github.com/SWEET1S/moonshine-roles-permissions/assets/73887319/c44ca3de-a964-4fb2-a31c-6ed72f9ac2a0)

If you use 'spatie/laravel-permission': '^6', everything is okay.

![The traits folder exists](https://github.com/SWEET1S/moonshine-roles-permissions/assets/73887319/b19b8911-b17f-4e5f-8d50-6c9ce942cb2f)

**Comment by SWEET1S** [comment]
Hi, thank you for your message. I have already made an update in Readme.MD
